### ISSUE TITLE
当年华不再，你如何依旧性感迷人？

### ISSUE THREAD

**Issue by alissli** [alissli/meinWorks-Creator#5]
大脑是最重要的性器官

可惜，很多人不懂，特别是具有我国特色的直男们

自卡尔维诺《如果在冬夜，一个旅人》之后，滞顿多年的大脑再次体会了高潮

原来，一部小说可以这样来写
原来，一个作者可以这样挑逗读者，步步为营，引向高潮

作为一个曾经的正经三好学生四有新人，少时阅读虽多且杂，但却从无涉及小黄文。二月河的《雍正皇帝》中隐晦的聚众淫乱的场景描写，彼时初读，已是震撼。彼时，到底是赤裸的文字更有力量，还是年轻身体的原始冲动太容易被唤起？

女性的处子之身，为什么被男权社会津津乐道，供上神坛？
答案是，单纯易控。
然而，文化这把双刃剑打造的另一面是：男性如若不能控制一个或者若干女性，那么他便失了男性气概和男性魅力。

世人常感慨：多年的夫妻牵手，不过是自己的左手牵起了右手。
看似互为一体水乳交融，却又隐隐透着一丝说不清、道不明的不甘。
张爱玲之”也许每一个男子全都有过这样的两个女人，至少两个。娶了红玫瑰，久而久之，红的变了墙上的一抹蚊子血，白的还是‘窗前明月光’；娶了白玫瑰，白的便是衣服上的一粒饭黏子，红的却是心口上一颗朱砂痣。“已成千年佳语。

星转斗移，世事转换。
人类在进化长河的经历积累了大量经验，与地球共生至今。
个人经历时间洗刷，起起落落，悲悲喜喜，经验带来成长，也带来偏见，一不小心，变成偏执。
中年人的乏味在于大部分已经谙熟社会规则，或高或低总能生存，顿时缺了年轻人的新奇劲儿
然而，伴随压抑的中国性文化，反向而生的却是黄段子在中年人之间的津津乐道

**Comment by zoeyzoey0102** [comment]
写得真好，开头一上来就颅内高潮了。

女人可以聪明，但不应该太聪明，风头盖过男人是不够聪明的。但再聪明都需要美貌打底，否则只会令人心生讨厌。我想这大概是全世界父权制社会体系下大部分直男对女人的刻板印象吧。

身为女人，你应该漂亮苗条，长相普通和赘肉一样不可忍受；

身为女人，你天生就该有母性，结婚后生儿育女是你的必然义务，未婚生育或丁克几乎就是大逆不道的；

身为女人，忠贞和操行是首要美德，恋爱史或性经验史不易太多，否则就是羞耻罪恶的；

女人在公开场合应该穿着检点，太暴露招来麻烦是咎由自取……

以及，中国男人大概只懂黄段子，不懂什么是真正的性魅力。
